---
- hosts: ["all"]
  become: true
  roles:
    - role: dimmaryanto93.proxy_repo
      vars: 
        proxy_url: http://192.168.88.50:8081/repository
        base:
          enabled: true
          name: centos-repository

- hosts: ["all"]
  become: true
  tasks:
    - name: Update apt-get repo and cache
      apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == 'Debian'

    - name: Upgrade all apt packages
      apt: 
        upgrade: dist 
        force_apt_get: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: upgrade all yum packages
      yum: 
        name: '*' 
        state: latest
      when: ansible_facts['os_family'] == 'RedHat'

- hosts: ["gitlab"]
  become: true
  roles:
    - role: dimmaryanto93.gitlab
      vars: 
        gitlab_external_url: "http://192.168.88.10"
        gitlab_root_password_print: true
        gitlab_init_root_password: default_password
        gitlab_init_shared_runner_registration_token: default_token

- hosts: ["registry"]
  become: true
  roles:
    - role: dimmaryanto93.oracle_java
      vars:
        ## download jdk from https://www.oracle.com/java/technologies/downloads/#java8-linux 
        ## TODO move downloaded file to files directory
        oracle_java_version: 8u311
    - role: dimmaryanto93.sonatype_nexus_oss
      vars:
        nexus_admin_password_print: true

- hosts: ["gitlab_runner"]
  become: true
  roles:
    - role: dimmaryanto93.gitlab_runner_docker_executor
      vars: 
        GITLAB_URL: "http://192.168.88.10"
        docker_storage_driver: overlay2
        gitlab_register_token: "default_token"
        docker_insecure_registries_enabled: true
        docker_insecure_registries_conf:
          - url: "192.168.88.9:8087"
            auth:
              docker_login: false      
              user: admin
              password: udemyAdminPassword
          - url: "192.168.88.9:8087"
            auth:
              docker_login: false      
              user: admin
              password: udemyAdminPassword